on:
  push:
    branches: [ 'main' ]
  # Used for testing before merging into main
  pull_request:
    types: [ opened, synchronize, reopened ]
    # types: closed

jobs:
  # Creates a git version tag
  git-tag:
    name: Create git version tag
    #Commented for testing | if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    outputs:
      tag: ${{steps.tag-step.outputs.tag}}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          #Commented for testing ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'

      - id: tag-step
        name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

  # Docker build
  docker:
    needs: git-tag
    #Commented for testing | if: github.event.pull_request.merged == true
    name: Create and publish a Docker image
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Build .jar file
        run: ./gradlew bootJar
      # Uses the `docker/login-action` action to log in to the Container registry.
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Uses docker/metadata-action to extract tags and labels that will be applied to the specified image.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      # Change image name to lower case
      - id: lowercase-image-name
        run: |
          echo "IMAGE_NAME_LOWER=${IMAGE_NAME@L}" >> "${GITHUB_ENV}"
      # Uses docker/build-push-action to build and push the docker image.
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:${{ needs.git-tag.outputs.tag }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LOWER }}:latest
          labels: ${{ steps.meta.outputs.labels }}
